### ISSUE TITLE
Enhancement: Convert code of conduct into rst page

### ISSUE THREAD

**Issue by JacobCoffee** [starlite-api/starlite-sphinx-theme#2]
### Summary

https://github.com/starlite-api/.github/blob/main/CODE_OF_CONDUCT.md

I would like to keep this, as GitHub adds these links to our repos automatically through community health files.

However, i do not like the fact that in our sphinx setup, clicking that link 
![image](https://user-images.githubusercontent.com/45884264/227106205-53588c98-c34d-4015-a780-f0685f88bd7b.png)
it takes me to GitHub. 

I feel like it should be embeded, as CONTRIBUTING.rst is.

**Comment by provinzkraut** [comment]
> I feel like it should be embeded

The idea was that the link on GitHub and the docs should lead to the same page. If we can change the link on GitHub to lead to a custom page, I'm fine with that and we can set up our CoC over at `starliteproject.dev`.

**Comment by JacobCoffee** [comment]
Unfortunately the community health files arent editable as far as I can tell 😢

**Comment by JacobCoffee** [comment]
Maybe it is best if we just keep it as it is for now because it would lead to making sure the github file and the docs file stay in sync? Im not sure here

**Comment by JacobCoffee** [comment]
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/


but as far as I can tell there is not way to make the CoC links go elsewhere

Django has this:
![image](https://user-images.githubusercontent.com/45884264/227223496-f070dbca-ee96-4f24-8e19-27d08df88be9.png)
https://docs.djangoproject.com/en/dev/internals/security/

And a small contributing file,
![image](https://user-images.githubusercontent.com/45884264/227223806-e81eab8f-737f-4d41-af17-fc5d3e966b7c.png)

 but it also points to https://docs.djangoproject.com/en/dev/internals/contributing/

**Comment by JacobCoffee** [comment]
We should just keep the github one for now
